version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rood
      POSTGRES_DB: YuriPass
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
